707 log slow checkpoints
savinay-vijay/mtools pull request #4
Opened 2019-07-04 14:17 UTC by mitesh-gosavi

**Description of changes**

The —checkpoint flag has been added to the argument parser for the mplotqueries. The parser, on receiving the —checkpoint flag, searches for loglines containing  the “Checkpoint took”  token (for reference, see https://github.com/mongodb/mongo/commit/f3eb44233050eee4da6aeaf4b4f93e9fb326a4d3). On encountering the token, the parser parses the token after “took” and typecast it to an integer to get the duration followed by mapping the details on to the graph.

**Testing**

The following testing tools have been used to test the newly added code:
1. Tox
2. Flake8
3. iSort
4. Doc8

2. The test result of a code coverage can be seen in table below:

**Name                                              Stmts   Miss  Cover
---------------------------------------------------------------------**

mtools/mplotqueries/mplotqueries.py                 400     93    77%
mtools/util/logevent.py                             510      2    99%

**Version Information**

| macOS 		| 10.14.5	|
| mongod		| v4.0.10	|
| MongoDB shell	| v4.0.10	|
| Python		| 2.7.10		|

2019-07-04 14:49 UTC, HenryGP requested changes
Some minor changes requested from my end :)

2019-07-04 14:49 UTC, HenryGP commented on mtools/util/logevent.py
> +            # SERVER-16176 log the checkpoints
Logging of **slow** checkpoints

2019-07-04 14:49 UTC, HenryGP commented on mtools/mplotqueries/mplotqueries.py
> +                                    help=("display the slow transactions "
It is actually slow WiredTiger checkpoints if I am not mistaken. This is not related to actual transactions.

2019-07-05 09:59 UTC, thiagogalesi reviewed
Some comments

2019-07-05 09:59 UTC, thiagogalesi commented on mtools/test/test_mplotqueries.py
> +        self.logfile_path = os.path.join(os.path.dirname(mtools.__file__),'test/logfiles/', filename)
btw, good practice 👍

2019-07-05 09:59 UTC, thiagogalesi commented on mtools/util/logevent.py
> +                self._duration = int(line_str[line_str.find("Checkpoint took") + len("Checkpoint took"): -20]) * 1000
See the comment on 706 on how to capture this with a regex

2019-07-05 12:03 UTC, manfontan commented on mtools/mplotqueries/mplotqueries.py
> +    import re
Review PEP style guide to sort imports https://www.python.org/dev/peps/pep-0008/#imports ;)

2019-07-05 12:05 UTC, manfontan commented on mtools/test/test_mplotqueries.py
> +import os
Review PEP style guide to sort imports https://www.python.org/dev/peps/pep-0008/#imports ;)

2019-07-08 11:03 UTC, HenryGP approved these changes

2019-07-08 13:23 UTC, davidedeangelismdb approved these changes

2019-07-09 12:21 UTC, thiagogalesi approved these changes

2019-07-09 12:21 UTC, thiagogalesi commented on mtools/util/logevent.py
> +            # SERVER-16176 - Logging of slow checkpoints
👍

2019-07-11 16:01 UTC, merged